version: '3'
services:
  node_one:
    build: ./node
    stdin_open: true
    depends_on:
      - redis
  redis:
    build: ./redis
  nginx:
    build: ./nginx
    ports:
      # Port 3000 will serve our static assets
      - "3000:3000"
      # Port 8080 will forward to our node server[s]
      - "3001:80"
    depends_on:
      - node_one