version: '3'
services:
  node_one:
    build: ./node
    stdin_open: true
    depends_on:
      - redis
  redis:
    build: ./redis
  nginx:
    build: ./nginx
    ports:
      # Port 3000 will serve our static assets
      - "80:80"
      # Port 3000 exposes our socket.io server
      - "3000:3000"
    depends_on:
      - node_one